[package]
name = "sguard-http"
version = "0.1.0"
edition = "2021"

[dependencies]
http = { workspace = true }
hyper = { workspace = true }
tokio = { workspace = true }
sguard-filter = { version = "0.1.0", path = "../sguard-filter", default-features = false }